---
apiVersion: v1
kind: Namespace
metadata:
  name: test-service
  labels:
    app.kubernetes.io/part-of: l2-applications
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: test-service
  labels:
    app: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:v1.10
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: test-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: whoami.lab.home
  labels:
    app: whoami
spec:
  type: LoadBalancer
  selector:
    app: whoami
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
