# ClusterSecretStore for HashiCorp Vault
# This connects External Secrets Operator to Vault
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      # Vault server address
      server: "http://vault.d.lcamaral.com"

      # Path to secrets engine (KV v2)
      path: "secret"
      version: "v2"

      # Authentication method: Token (simplest for homelab)
      # For production, use Kubernetes auth or AppRole
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: "external-secrets"
