# Talos Worker Machine Configuration Template
# This is a Go template used by Karpenter to generate worker configs
# Values are injected from secret-talos-values.yaml
apiVersion: v1
kind: Secret
metadata:
  name: karpenter-talos-template
  namespace: kube-system
  labels:
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/component: talos-template
type: Opaque
stringData:
  user-data: |
    version: v1alpha1
    debug: false
    persist: true
    machine:
      type: worker
      token: {{ .Values.machineToken }}
      ca:
        crt: {{ .Values.machineCA }}
      certSANs: []
      kubelet:
        image: ghcr.io/siderolabs/kubelet:{{ .Values.kubeletVersion }}
        extraArgs:
          rotate-server-certificates: "true"
        registerWithTaints:
          - key: "karpenter.sh/unregistered"
            effect: "NoExecute"
        nodeIP:
          validSubnets:
            - 192.168.100.0/24
      network:
        hostname: "{{ .Metadata.Hostname }}"
        interfaces:
          - deviceSelector:
              physical: true
            dhcp: true
            mtu: 1500
      install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v{{ .Values.talosVersion }}
        wipe: true
      time:
        servers:
          - 192.168.4.1
          - time.cloudflare.com
      features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
    cluster:
      id: {{ .Values.clusterID }}
      secret: {{ .Values.clusterSecret }}
      controlPlane:
        endpoint: {{ .Values.clusterEndpoint }}
      clusterName: {{ .Values.clusterName }}
      network:
        cni:
          name: none
        podSubnets:
          - 10.244.0.0/16
        serviceSubnets:
          - 10.96.0.0/12
      proxy:
        disabled: true
      token: {{ .Kubernetes.BootstrapToken }}
      ca:
        crt: {{ .Kubernetes.RootCA | b64enc | quote }}