# NFS Provisioner Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
  labels:
    app.kubernetes.io/name: nfs-provisioner
    app.kubernetes.io/component: storage
    platform.kubernetes.io/layer: l1
